### ISSUE TITLE
Design : Overall revision

### ISSUE THREAD

**Issue by gmkim20713** [team15ya/WeatherWear#44]
[상세 내용]
- Main 페이지 Recommendation area 헤더
- Main 페이지 Recommendation area 전반적인 규격 (잘리던 이미지 수정)
- Main 페이지 Catergory name area
- Main 페이지 ScrollView
- Main 페이지 Daylist 버튼 (원형으로 수정 + 콘솔함수 수정)
- Location 페이지 'Done' 버튼

**Comment by Jungeunkim-dev** [comment]
[상세 내용]

Mainpage 
- [ ] 상단 컴포넌트 'general' 정렬 방식 수정
(추가중)

**Comment by gmkim20713** [comment]
[상세 내용]
- Constitution setting button 규격 수정
